[package]
name = "fenix-core"
version = "0.1.0"
edition = "2021"
description = "Fenix app core functionalities"

[dependencies]
log = "0.4.17"   
chrono = "0.4.23"
fern = { version = "0.6.1", features = ["colored"] }   
