[workspace]
resolver = "2"
members = [
  "fenix-core",
  "fenix-renderer",
  "fenix-utils",
  "fenix-app",
]

default-members = [
  "fenix-app"
]

[profile.release]
lto = "thin"

[profile.opt]
inherits = "release"
lto = "fat"
opt-level = 3
