comment_width = 80
edition = "2021"
match_block_trailing_comma = true
max_width = 100
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
wrap_comments = true
